version: "2"
services:
   docker_moodle-app:
     build:
      context: Docker/
      dockerfile: PHP.Dockerfile
     restart: always
     container_name: docker_moodle-app
     volumes:
       - ./src/moodle:/var/www/html
       - ./src/moodledata:/var/www/moodledata
       - ./Docker/conf/local.ini:/usr/local/etc/php/php.ini
     networks:
       - docker_moodle
     depends_on:
       - docker_moodle-db
   docker_moodle-web:
     image: nginx
     restart: always
     container_name: docker_moodle-web
     volumes:
       - ./Docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
     volumes_from:
       - docker_moodle-app
     ports:
     - "8088:8088"
     networks:
       - docker_moodle
   docker_moodle-db:
     image: arm64v8/mariadb:10.6
     restart: always
     container_name: docker_moodle-db
     environment:
           - MYSQL_USER=moodledude
           - MYSQL_PASSWORD=mysecretpassword
           - MYSQL_DATABASE=moodle
           - MYSQL_ALLOW_EMPTY_PASSWORD=true
     volumes:
           - ./Docker/dbdata:/var/lib/mysql
           - ./Docker/conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
     expose:
           - "3306"
     networks:
           - docker_moodle
   docker_moodle-cron:
      container_name: docker_moodle-cron
      build:
        context: Docker/
        dockerfile: Cron.Dockerfile
      volumes_from:
        - docker_moodle-app
      restart: always
      volumes:
        - ./Docker/log/cron:/var/log/cron
      networks:
        - docker_moodle
      depends_on:
        - docker_moodle-db

networks:
  docker_moodle:
      external: false

